#=========================== Filebeat prospectors =============================
filebeat.prospectors:
- type: log
  encoding: utf-8
  paths:
    - /home/app/log/logstash_*.log
  json.keys_under_root: true
  json.add_error_key: true

#================================ Outputs =====================================

name: ${FILEBEAT_APP_NAME:app}

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["${FILEBEAT_ELASTICSEARCH_HOSTS:localhost:9200}"]
  index: "${FILEBEAT_APP_NAME:app}-%{+yyyy.MM}"

setup.template:
  name: "${FILEBEAT_APP_NAME:app}"
  pattern: "${FILEBEAT_APP_NAME:app}-*"

setup.dashboards.index: "${FILEBEAT_APP_NAME:app}-*"
setup.dashboards.enabled: false
